apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-springboot-app.fullname" . }}
  annotations:
    prometheus.io/port: 8080
    prometheus.io/scrape: "true"
  labels:
    {{- include "simple-springboot-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-springboot-app.selectorLabels" . | nindent 4 }}
