kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: webhook_demo
        # Send severity=medium alerts to url.
          match:
            severity: medium
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: to_email@email.com
        send_resolved: false
        from: from_email@email.com
        smarthost: smtp.email.com:25
        require_tls: false
    - name: webhook_demo
      webhook_configs:
      - url: https://webhook-url:9091/alertPost
